### ISSUE TITLE
README doc link 404's

### ISSUE THREAD

**Issue by jgrosso** [lexi-lambda/hackett#101]
The link on the README to the docs goes to https://docs.racket-lang.org/hackett@hackett-doc/, which (for me at least) 404's (`> ((uncaught-exception-handler)\n(*(+(*)(*(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*))))(+(*)(*)(*)(*))))\nuncaught exception: 404`). I'd be happy to make a quick PR; is there an updated link to the docs to use instead?

**Comment by sorawee** [comment]
https://lexi-lambda.github.io/hackett/ I think.

**Comment by jgrosso** [comment]
@sorawee thanks!
