### ISSUE TITLE
Leading upper case. 

### ISSUE THREAD

**Issue by AnthonyJacob** [lexi-lambda/hackett#16]
When going trough the example I found that constructors do not start with upper case. 

Could you give an explanation why? 

Can type names also start with lowercase?

**Comment by lexi-lambda** [comment]
Yes, there is no required lexical distinction between any sort of binding. In a macro-enabled language, it doesn’t make a whole lot of sense to assign so much meaning to the *names* of identifiers. By convention, type names and typeclasses still start with uppercase identifiers, but all values start with lowercase letters.
