### ISSUE TITLE
Multi-value case expressions

### ISSUE THREAD

**Issue by lexi-lambda** [lexi-lambda/hackett#27]
Currently, `case` can only match against one value at a time. It would be nice if there were a `case*` that could match upon any number of values at once, like this:

```racket
(case* [x y]
  [[(just a) (just b)] (just (tuple a b))]
  [[nothing  nothing]  nothing])
```

Since there can only ever be one expression on the right hand side of a `case*` expression, we could also drop the additional grouping brackets. However, that might be sort of hard to read. To alleviate, we could introduce a literal to make the syntax easier to visually parse:

```racket
(case* [x y]
  [(just a) (just b) -> (just (tuple a b))]
  [nothing  nothing  -> nothing])
```

I personally like this syntax, but some people might find it un-lispy. We’d also have to decide if `case` should also use the literal or not.

**Comment by greghendershott** [comment]
This is an excellent bike-shedding topic. :smile:

- I like the symmetry of `[x y]` and `[pattern pattern]` in 1.

- Some people like "structural" sexp nav/editing tools (like paredit and smart-parens for Emacs, and the equivalents for Vim, DrRacket, and so on). That's a point in favor of 1.

- Similarly various tools that indent sexprs will just-work with 1.  Example:

```
;; with 1
(case* [x y]
  [[(just a) (just b)]
   (some very long expression on another line)]
  [[nothing  nothing] nothing])

;; with 2, you're likely to get something like:
(case* [x y]
  [(just a) (just b)
            -> (some very long expression on another line)]
  [nothing  nothing  -> nothing])
```

- If parens are bad, why stop with 2?  Why not eliminate the brackets around the case clauses, too? This is a slippery slope and soon you'll need to rename it Hojure. :grin:

Having said all that, this is still bike-shedding and 2 would probably be fine.

I suppose the meta-point is maybe just, the more you stick with sexprs, the less you need to think about syntax, as a designer or a user. /shrug

**Comment by lexi-lambda** [comment]
The point about indentation is probably the strongest point I’ve heard in favor of 1, and it’s potentially strong enough to swing me into the first camp. The symmetry is nice, too, but it’s somewhat less important to me. I think that the multiline case clauses look nicer with point 1, but the single-line clauses look nicer with 2. :(

I worry that the proliferation of parentheses will be difficult to read, especially since I imagine most definitions will use a definition variant of `case*` that looks like this:

```racket
(def+ foo : (forall [a b] {(just a) -> (just b) -> (just (tuple a b))})
  [[(just x) (just y)] (just (tuple a b))]
  [[_        _       ] nothing])
```

Maybe that’s not so bad, though. I sort of worry it will be worse for single-argument functions:

```racket
(def+ tail : (forall [a] {(List a) -> (Maybe (List a))})
  [[{_ :: xs}] (just xs)]
  [[nil      ] nothing])
```

But again, that doesn’t seem *so* horrible. I’m not sure. Sticking with option 1 seems like it could be safer to start with, though.

**Comment by bwo** [comment]
> I personally like this syntax, but some people might find it un-lispy

To me it actually suggests the `=>` syntax for `cond`. (Whether that's good or bad, I have no idea.)

**Comment by fiddlerwoaroof** [comment]
For what it's worth, as far as my editing workflow goes, I find the extra clutter of various parentheses/braces/etc. is more than balanced by the fact that emacs commands like `paredit-splice-sexp-kill-forward` and `paredit-splice-sexp-kill-backwards` do the right thing.
