### ISSUE TITLE
regression: typeclasses are broken in the repl

### ISSUE THREAD

**Issue by gelisam** [lexi-lambda/hackett#35]
Observed behaviour:

    $ racket -I hackett
    > (++ "foo" "bar")
    ; @%dictionary-placeholder: should never appear at runtime [,bt for context]
    > (show 42)
    ; @%dictionary-placeholder: should never appear at runtime [,bt for context]

Previous, expected behaviour:

    $ racket -I hackett
    > (++ "foo" "bar")
    : String
    "foobar"
    > (show 42)
    : String
    "42"

**Comment by gelisam** [comment]
`git bisect` blames commit ba0907815e48747e39d5e1fd920f6b4dc83efb3a for this regression. That commit is about `#%top-interaction`, which suggests the following follow-up test: can I use type-classes if I'm not at the top-level?

    $ racket -I hackett
    > (def x (++ "foo" "bar"))
    > x
    : String
    "foobar"

I can!

**Comment by lexi-lambda** [comment]
I’m pretty sure I noticed and already fixed this in 5e1bbeda8515911ed170eec16edb60b6e0e4c673, though a test would be good. Are you running the latest version?

**Comment by gelisam** [comment]
Oops! Indeed, sorry for the noise.
