### ISSUE TITLE
Exhaustiveness checking for pattern-matching

### ISSUE THREAD

**Issue by lexi-lambda** [lexi-lambda/hackett#4]

**Comment by Shamrock-Frost** [comment]
I'd like to help with this when I have more time, but until then, [here's a paper](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/08/gadtpm-acm.pdf) which I think would be worth looking at so exhaustive checking works if/when GADTs are supported.

**Comment by lexi-lambda** [comment]
I think implementing that is overkill, given that Hackett does not have GADTs and may not for some time. It would be better to implement a much simpler algorithm until it’s necessary/desirable to add more complexity.

**Comment by iitalics** [comment]
I'm interested in implementing this, but I forsee a small issue with error messages and rename-in. Something like:

```racket
(require (rename-in hackett [right left]))
(case (left 0)
  [(left x)  x])
;; error: non-exhaustive pattern. pattern '(left _)' is not matched
```

Is this a problem?

**Comment by lexi-lambda** [comment]
> Is this a problem?

If it is, I don’t think it’s easily solvable. One solution would be to look for identifiers that are symbolically equal, and if they are, qualify them by module path. That’s essentially what GHC does in various situations, I think.

That said, I don’t mind that being a problem right now. I think, right now, there’s little evidence to suggest that anyone would reasonably do such a thing. Improvements are always possible once the basic implementation is in place, and exhaustiveness checking with less-than-perfect error messages is still better than no exhaustiveness checking at all.
