### ISSUE TITLE
type safe variadic functions

### ISSUE THREAD

**Issue by bmabsout** [lexi-lambda/hackett#50]
maybe it might be nice having functions with types (or kinds)  `a -> a -> a`  become variadic automatically?
for example `(:: 1 2 3 4 nil)` would be a list, `(>>= applyfirst applysecond applythird)` would be monadic computations, `(-> (Maybe a) a a)` would be a function of type `{(Maybe a) -> a -> a}`. I was reading Hackett's guide and I was thinking is there a reason why it isn't so?

**Comment by iitalics** [comment]
This doesn't work so well during type inference when you don't know how many arguments a function takes yet

**Comment by bmabsout** [comment]
can't you count the arguments? it's a list after all and should be unambiguous syntax wise.

**Comment by iitalics** [comment]
Take for example: `(λ [f] (f 1 2 3))` , what is the type here?

**Comment by bmabsout** [comment]
ah I see what you mean, so in this case it could be `a -> a -> a` or `a -> a -> a -> a`, so there's no solution for this?

**Comment by bmabsout** [comment]
you can always force the user to put a type for such a case

**Comment by bmabsout** [comment]
unless a third type of bracket is introduced but that would be alot of brackets

**Comment by iitalics** [comment]
It's up to lexi to decide if this is worth reducing the inference capabilities. I like the idea of bracketting, or even using a reader macro since were going to run out of brackets soon. But I don't know if this is all that necessary -- infix operators already do the job pretty well:

```scheme
{1 :: 2 :: 3 :: 4 :: nil}

{m >>= f >>= g >>= h}
```

**Comment by gelisam** [comment]
The normal-brackets version is a code-to-code transformation which needs to
know the type of functions in the code it transforms. This sounds like an
excellent test case for the macro system which Hackett wants to have, in
which macros can receive information from the type system!

**Comment by bmabsout** [comment]
it isn't very necessary but it's kind of nice

**Comment by lexi-lambda** [comment]
I am very wary of these sorts of conveniences that seem simple but require global, ad-hoc rules that affect type inference. As @gelisam mentions, this could probably be implemented as a userland macro, and in fact it probably doesn’t even need access to type information—it just needs to “unroll” its arguments. I don’t want to do this automatically, though.
