### ISSUE TITLE
Case pattern expanders?

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/hackett#75]
For the module language @iitalics and I are working on, we would like to define macros that can expand in _case-pattern_ positions, similar to how match expanders let us define macros that can expand in _match-pattern_ positions in `racket/match`.

The specific use case we have is a case-pattern-expander for the `#%dot` form, so that for example `(case x [(M.Constructor1 ....) ....] [(M.Constructor2 ....) ....])` can expand to something like `(case x [(internal-Constructor1 ....) ....] [(internal-Constructor2 ....) ....])` when `M` is a module that defines a datatype with those constructors.

**Comment by lexi-lambda** [comment]
I agree, I’d like such a thing, too, and I’ve been planning to implement it at some point. That said, I actually *don’t* want to do it the way custom expanders are typically implemented in Racket. Instead, I think I’d like to try to apply the same “custom core forms” technique used in the type language to create a custom “pattern language”. It might not be meaningfully different at first, but I think it could open up avenues later, and I think it’s a nice technique.

**Comment by AlexKnauth** [comment]
Does the "expand to custom core forms approach" allow one identifier having both a case-pattern-expander behavior and a normal macro behavior?

**Comment by lexi-lambda** [comment]
Perhaps you’re right. We *don’t* want a separate namespace for patterns, since they should share the value namespace, so it’s unclear if that’s the right thing to do. I’ll think about if it makes sense to do something fancier, but I think you’re right that the traditional solution is the right thing for now.
