### ISSUE TITLE
Indendation sensitivity 

### ISSUE THREAD

**Issue by ShalokShalom** [lexi-lambda/hackett#96]
Hi there :)

I am new to Racket, Haskell and programming at all. :D

I found that both, the macro system of Racket and the ML syntax of Haskell please me a lot.

I found some syntax changes to Racket like [Sweet](https://docs.racket-lang.org/sweet/index.html), which goes into the direction of traditional "indentation for building blocks" philosophy, while they are not going far enough for me personally. 

This is a proposal for an alternative syntax, [like fsharp does it](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/verbose-syntax): 

They released their language initially with the OCaml like ```in end``` method and provided additionally the so-called light syntax which uses indentation instead. Their community adopted the latter one extremely well and quick, so it is their standard today.

I honestly think that members from both communities might prefer a very similar approach here, since Hackett builds a bridge between Haskell and Racket. 

I for myself discovered, that ML languages with an indentation-sensitive syntax are by far the most readable and least scary programming languages.

Thanks a lot for reading :)

**Comment by lexi-lambda** [comment]
This is a duplicate of #22.
